### ISSUE TITLE
Assign Azure Reader role to Azure Purview MSI at Data Landing Zone subscription 

### ISSUE THREAD

**Issue by zeinab-mk** [Azure/data-landing-zone#115]
When Data Landing Zone is deployed, it is nice to have Azure RBAC Reader role automatically assigned to Azure Purview MSI at subscription level. This step is required so customers can register and scan data sources in Purview.

**Comment by marvinbuss** [comment]
We will not add this for now, since SHIR and Service Principal are required anyways for scans, if all services are behind private endpoints (e.g. Purview, Synapse, Data Factory, etc.). Therefore, we will hold off for now, since this is not something that is actually required when using private endpoints end-to-end.
