### ISSUE TITLE
After deletion of DLZ, the prefix check fails with error - Prefix currently unavailable. Please choose a different one.

### ISSUE THREAD

**Issue by renepajta** [Azure/data-landing-zone#159]
**Describe the bug**
After deletion of DLZ, the prefix check fails with error - Prefix currently unavailable. Please choose a different one.

**Steps to reproduce**

1.  Deploy DLZ
2.  Delete DLZ
3.  Check all resource groups are gone
4. Deploy DLZ again

**Screenshots**
![image](https://user-images.githubusercontent.com/6043628/127857526-f050d9e8-ae05-4b0c-8390-66fcb63813c0.png)
![image](https://user-images.githubusercontent.com/6043628/127857543-37cd4e81-9d81-43b3-ad11-b3e88627bf47.png)

**Comment by marvinbuss** [comment]
@renepajta Yes, this behavior is expected. The Key Vaults do not get fully deleted. They have purge protection enabled. This means, if you delete your Data Landing Zone and redeploy it with the same settings, it will still show you that the prefix is already taken, since the Key Vaults already exist in a soft-deleted state. They are completely removed after 30 days.
I a prod customer environment this is a good behavior, because you don't want to accidently loose secrets and certificates.

**Comment by renepajta** [comment]
I see and totally make sense. I will close the issue then.
