### ISSUE TITLE
Bug: Synapse does not have access to the Storage accounts RAW,etc.

### ISSUE THREAD

**Issue by MiguelElGallo** [Azure/data-landing-zone#231]
### Deployment Mode

Azure DevOps

### Steps to reproduce

Standard deployment.
Then from AZURE workspace try lo link any of the Storage accounts like RAW. Synapse Cannot see the endpoints. Synapse Identity is lacking permission.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Azure/data-landing-zone/blob/main/CODE_OF_CONDUCT.md)

**Comment by marvinbuss** [comment]
Hi @MiguelElGallo.
The Synapse workspace has access (Storage Blob Data Contributor) to its default storage file system ("data" file system in the workspace layer).

The role assignment is done here: https://github.com/Azure/data-landing-zone/blob/f7fcb357e8c759e41333dfdff33f6f9837c07552/infra/modules/sharedproduct.bicep#L67-L74 

We are not assigning any additional roles as the access most often needs to be more granular and defined on the POSIX ACL layer to apply more granular access controls.
What kind of access are you looking for?

**Comment by MiguelElGallo** [comment]
Hi, 
The idea represented in a picture:
![image](https://user-images.githubusercontent.com/60221874/151507122-01c87596-adbd-403c-b51d-697d31ff5325.png)

**Comment by MiguelElGallo** [comment]
Aso the Share Integration should be Optional, since Synapse has an "embedded" data factory.

**Comment by marvinbuss** [comment]
> Hi, I was referring to the RAW storage account for example. Our first use case is: In container _data_ inside _RAW_ , some files will be written. Then in Synapse we will create a linked service to that Storage Account, and create some external tables based on those files. But Synapse cannot access those Storage Accounts. Is there any documentation of how you are supposed to access those storage accounts? It says AD access is disabled. Thanks!

Hi @MiguelElGallo,
To access these Storage Accounts, you will have to create a managed private endpoint first and then you have to create a linked service for that storage. In addition , you will have to grant the Synapse MSI access rights on the storage account.
For more details, please visit these links:
* [Managed Private Endpoint](https://docs.microsoft.com/en-us/azure/synapse-analytics/security/how-to-create-managed-private-endpoints#:~:text=%20Create%20a%20Managed%20private%20endpoint%20to%20your,window%2C%20enter%20information%20about%20the%20data...%20More%20)
* [Grant permissions](https://docs.microsoft.com/en-us/azure/synapse-analytics/security/how-to-grant-workspace-managed-identity-permissions#grant-permissions-to-managed-identity-after-workspace-creation)

The creation of managed private endpoints cannot be automated at this point in time, because this is on the data plane of Synapse. Hence, ARM is not able to access the endpoint, as we are deploying Synapse with private endpoints and disabled public network access. Also, we are not deploying any additional role assignments, as the access requirements highly depend on the customer scenario. This is why we are only assigning access rights to the primary Data Lake Fiel System.


> Aso the Share Integration should be Optional, since Synapse has an "embedded" data factory.

For this question, I would like you to check this Discussion: https://github.com/Azure/data-landing-zone/discussions/193
What you are rather asking us to do is to replace the ADF instance in the shared integration RG with a Synapse instance. That is a very good suggestion and something we should offer. The Synapse instance in the shared product RG is more used for data product teams to do ad-hoc analysis and for a highly scalable Spark engine on Databricks.

**Comment by MiguelElGallo** [comment]
Hi @marvinbuss thanks and understood.
This part "you will have to grant the Synapse MSI access rights on the storage account" is the one that we are wondering. Because those storage accounts have "AD auth disable", will this work ?
Thanks,
Miguel

**Comment by marvinbuss** [comment]
Hi @MiguelElGallo, yes that will work. We have not disabled AAD authentication. We have only disabled Key-based authentication using this parameter:
https://github.com/Azure/data-landing-zone/blob/f7fcb357e8c759e41333dfdff33f6f9837c07552/infra/modules/services/storage.bicep#L82

**Comment by marvinbuss** [comment]
Hi @MiguelElGallo,
Can this be closed or is any further guidance required?

**Comment by MiguelElGallo** [comment]
Hi @marvinbuss , this can be closed. Thanks!

**Comment by marvinbuss** [comment]
Thanks @MiguelElGallo! 👍
